### ISSUE TITLE
no-gratuitous-expressions: TypeError: Cannot read property 'references' of null

### ISSUE THREAD

**Issue by adamhl8** [SonarSource/eslint-plugin-sonarjs#271]
**I want to report a bug.**

An error is thrown if an if statement uses a variable that is set to the result of a function that returns a bool. If the function is called directly inside the if statement, no error is thrown.  I'm using `@typescript-eslint/parser`.

**Reproducer**

Throws error:
```
const foo = bar()

if (foo) {
  // doSomething()
} else {
  // doSomethingElse()
}

function bar(): boolean {
  let someBool = // ...
  return someBool
}
```

No errors:
```
if (bar()) {
  // doSomething()
} else {
  // doSomethingElse()
}

function bar(): boolean {
  let someBool = // ...
  return someBool
}
```
___
```
Oops! Something went wrong! :(

ESLint: 7.30.0

TypeError: Cannot read property 'references' of null
Occurred while linting /home/adam/dev/password-test/src/index.ts:27
    at /home/adam/dev/password-test/node_modules/eslint-plugin-sonarjs/lib/rules/no-gratuitous-expressions.js:175:39
    at Array.map (<anonymous>)
    at transformAndFilter (/home/adam/dev/password-test/node_modules/eslint-plugin-sonarjs/lib/rules/no-gratuitous-expressions.js:175:10)
    at :statement (/home/adam/dev/password-test/node_modules/eslint-plugin-sonarjs/lib/rules/no-gratuitous-expressions.js:57:58)
    at /home/adam/dev/password-test/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/adam/dev/password-test/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/adam/dev/password-test/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/adam/dev/password-test/node_modules/eslint/lib/linter/node-event-generator.js:320:22)
    at NodeEventGenerator.enterNode (/home/adam/dev/password-test/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
```

**Comment by yassin-kammoun-sonarsource** [comment]
Hey @adamhl8, I didn0t manage to reproduce this error alone with the code snippet you provided. Would you mind sharing your `.eslintrc.js` config file as well ?

Also, that would be nice if you could tell us which version of @typescript-eslint/parser and typescript you are using.

**Comment by adamhl8** [comment]
I've made a repo that reproduces the issue so you can see all my configs/package versions.

https://github.com/adamhl8/eslint-plugin-sonarjs-271

**Comment by yassin-kammoun-sonarsource** [comment]
Thanks, I was able to reproduce the type error using your repository. For reasons that still remain unclear to me, the type error only happens when using `@typescript-eslint/recommended`. ESLint scope manager handles differently the global scope of the program with this recommended profile, which ends up impacting the behaviour of the rule.

A fix is on its way.
